apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: key-repo
  name: key-repo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: key-repo
    spec:
      containers:
      - image: luismoramedina/key-repo
        imagePullPolicy: Always
        name: key-repo
---
apiVersion: v1
kind: Service
metadata:
  name: key-repo
  labels:
    app: key-repo
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: key-repo
---
